rising/Student/urls.py
from django.conf.urls import url
from Student import views

app_name='Student'

urlpatterns = [
        url(r'^registration/', views.register, name='register'),
        url(r'^login/', views.user_login, name='user_login'),
        url(r'^Dashboard/', views.Dashboard, name='dashboard'),
        url(r'^index/', views.index, name='index'),
]

rising/Trainer/urls.py
from django.conf.urls import url
from Trainer import views

app_name='Trainer'

urlpatterns = [
        url(r'^registration/', views.register, name='register'),
        url(r'^login/', views.user_login, name='user_login'),
        url(r'^Dashboard/', views.Dashboard, name='dashboard'),
]

rising/rising/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from Trainer import views
urlpatterns = [
    url(r'admin/', admin.site.urls),
    url(r'^$', views.user_login, name='user_login'),
    url(r'Trainer/', include('Trainer.urls')),
    url(r'Student/', include('Student.urls')),
    url(r'^logout/', views.user_logout, name='logout'),
]

from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rising/Student/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class StudentProfileInfo(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    phone = models.CharField(max_length=12)

    def __str__(self):
        return self.user.username

class Feedback(models.Model):
    datestamp = models.DateField(auto_now_add=True)
    liked = models.CharField(max_length=50, default="")

rising/Trainer/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    phone = models.CharField(max_length=12)
    topic = models.CharField(max_length=50, default="")

    def __str__(self):
        return self.user.username

class Document(models.Model):
    datestamp = models.DateField(auto_now_add=True)
    document = models.FileField(upload_to='documents/')
    title = models.CharField(max_length=50)
    topic = models.CharField(max_length=50, default="")

rising/Student/forms.py
from django import forms
from django.contrib.auth.models import User
from Student.models import StudentProfileInfo

class StudentForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ("username", "email", "password")

class StudentProfileInfoForm(forms.ModelForm):

    class Meta():
        model = StudentProfileInfo
        fields = ("phone",)

rising/Trainer/forms.py
from django import forms
from django.contrib.auth.models import User
from Trainer.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ("username", "email", "password")

class UserProfileInfoForm(forms.ModelForm):

    class Meta():
        model = UserProfileInfo
        fields = ("phone","topic")

rising/Student/views.py
from django.shortcuts import render
from Student.forms import StudentForm, StudentProfileInfoForm

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from Student.models import Feedback, StudentProfileInfo
# Create your views here.
def index(request):
    return render(request, 'Student/index.html')

def Dashboard(request, docRecs):

    # return render(request, "Student/Dashboard.html", context=docRecs)
    return render(request, 'Student/index.html')

def register(request):
    registered=False

    if request.method=="POST":
        user_form = StudentForm(data=request.POST)
        profile_form = StudentProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user

            profile.save()
            registered=True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = StudentForm()
        profile_form = StudentProfileInfoForm()
    return render(request, 'Student/registration.html', {'user_form': user_form, 'profile_form': profile_form, 'registered': registered})

@login_required
def user_logout(request):
    logout(request)
    # return HttpResponseRedirect(reverse('index'))
    return render(request, 'Student/login.html', {})

def user_login(request):
    if request.method=='POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                # record = UserProfileInfo.objects.get(user=user)
                # userRec = {'record':record}
                # userTopic = str(userRec['record'].topic)
                # docrec = Document.objects.filter(topic=userTopic)
                # docRecs = {'docrec':docrec}
                # return HttpResponseRedirect(reverse('index'))
                # return render(request, "Student/Dashboard.html", context=docRecs)
                return render(request, "Student/index.html")
            else:
                return HttpResponse("account not active")
        else:
            print("error....\nlogin failed")
            print("username: {} password: {}".format(username,password))
            return HttpResponse("invalid login details")
    else:
        return render(request, 'Student/login.html', {})

rising/Trainer/views.py
from django.shortcuts import render
from Trainer.forms import UserForm, UserProfileInfoForm

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from Trainer.models import Document, UserProfileInfo
# Create your views here.
def index(request):
    return render(request, 'Trainer/index.html')

def Dashboard(request, docRecs):

    return render(request, "Trainer/Dashboard.html", context=docRecs)

def register(request):
    registered=False

    if request.method=="POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user

            profile.save()
            registered=True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    return render(request, 'Trainer/registration.html', {'user_form': user_form, 'profile_form': profile_form, 'registered': registered})

@login_required
def user_logout(request):
    logout(request)
    # return HttpResponseRedirect(reverse('index'))
    return render(request, 'Trainer/login.html', {})

def user_login(request):
    if request.method=='POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                record = UserProfileInfo.objects.get(user=user)
                userRec = {'record':record}
                userTopic = str(userRec['record'].topic)
                docrec = Document.objects.filter(topic=userTopic)
                docRecs = {'docrec':docrec}
                # return HttpResponseRedirect(reverse('index'))
                return render(request, "Trainer/Dashboard.html", context=docRecs)
            else:
                return HttpResponse("account not active")
        else:
            print("error....\nlogin failed")
            print("username: {} password: {}".format(username,password))
            return HttpResponse("invalid login details")
    else:
        return render(request, 'Trainer/login.html', {})

rising/templates/Student/Dashboard.html
<!DOCTYPE html>
{% extends 'navbarBase.html' %}
{% load staticfiles %}

{% block mainblock %}
<div class="container" style="margin: 20px 40px;">
  <h1><p style="align-text: center">Study Material</p></h1>
  <div style="display: flex; flex-flow: row wrap; ">
    {% for data in docrec %}

      <div class="card" style="width: 18rem; margin: 2px 4px;">
        <!-- <img src="{% static 'Trainer/img/pdf.jpg' %}" class="card-img-top" alt="..."> -->
        <div class="card-body">
          <h5 class="card-title">{{ data.title }}</h5>
          <p class="card-text"><strong>Topic:</strong> {{ data.topic }}</p>
          <a href="/media/{{ data.document }}" target="_blank" class="btn btn-primary">Start</a>
        </div>
      </div>

    {% endfor %}
  </div>
</div>
{% endblock %}

rising/templates/Student/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body>
    <a href="{% url 'Trainer:register' %}">register</a>

    {% if user.is_authenticated %}
    <a href="{% url 'logout' %}">logout</a>
    {% else %}
    <a href="{% url 'Trainer:user_login' %}">login</a>
    {% endif %}

  <div class="container">
    {% block mainblock %}
    {% endblock %}
  </div>
  </body>
</html>

rising/templates/Student/index.html
<!DOCTYPE html>
{% extends 'navbarBase.html' %}
{% load staticfiles %}
{% block mainblock %}
<div class="jumbotron">
  <h1>hello</h1>
</div>
{% endblock %}

rising/templates/Student/login.html
<!DOCTYPE html>
{% extends 'loginBase.html' %}
{% load staticfiles %}
<body>
	{% block loginblock %}
	<div class="row">
		<div class="col-12">
			<ul class="nav nav-pills nav-fill">
					<li class="nav-item"><a href="{% url 'Trainer:user_login' %}" class="nav-link">Trainer</a></li>
					<li class="nav-item"><a href="{% url 'Student:user_login' %}" class="nav-link active">Student</a></li>
			</ul>
		</div>
	</div>
	<br>
	<div class="row">
		<div class="col-12">
			<form action="{% url 'Student:user_login' %}" method="post">
					{% csrf_token %}
					<div class="form-group">
						<labe for="username" >Username: </labe>
    					<input type="text" name="username" placeholder="enter username">
						<labe for="password" >password: </labe>
						<input type="text" name="password" placeholder="enter password">					
					</div>
					<input type="submit" name="" value="Login">
			</form>
		</div>
	</div>
	{% endblock %}
</body>

rising/templates/Student/registration.html
<!DOCTYPE html>
{% extends 'Student/base.html' %}
{% load staticfiles %}
{% block mainblock %}
<div class="jumbotron">
  {% if registered %}
  <p>thanks</p>
  {% else %}
  <p>register here</p>

  <form action="" method="post">
    {% csrf_token %}
    {{ user_form.as_p }}
    {{ profile_form.as_p }}
    <input type="submit" name="" value="Register">
  </form>
  {% endif %}
</div>
{% endblock %}

rising/templates/Trainer/Dashboard.html
<!DOCTYPE html>
{% extends 'navbarBase.html' %}
{% load staticfiles %}

{% block mainblock %}
<div class="container" style="margin: 20px 40px;">
  <h1><p style="align-text: center">Study Material</p></h1>
  <div style="display: flex; flex-flow: row wrap; ">
    {% for data in docrec %}

      <div class="card" style="width: 18rem; margin: 2px 4px;">
        <!-- <img src="{% static 'Trainer/img/pdf.jpg' %}" class="card-img-top" alt="..."> -->
        <div class="card-body">
          <h5 class="card-title">{{ data.title }}</h5>
          <p class="card-text"><strong>Topic:</strong> {{ data.topic }}</p>
          <a href="/media/{{ data.document }}" target="_blank" class="btn btn-primary">Start</a>
        </div>
      </div>

    {% endfor %}
  </div>
</div>
{% endblock %}

rising/templates/Trainer/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body>
    <a href="{% url 'Trainer:register' %}">register</a>

    {% if user.is_authenticated %}
    <a href="{% url 'logout' %}">logout</a>
    {% else %}
    <a href="{% url 'Trainer:user_login' %}">login</a>
    {% endif %}

  <div class="container">
    {% block mainblock %}
    {% endblock %}
  </div>
  </body>
</html>

rising/templates/Trainer/index.html
<!DOCTYPE html>
{% extends 'loginBase.html' %}
{% load staticfiles %}
{% block mainblock %}
<div class="jumbotron">
  <h1>hello</h1>
</div>
{% endblock %}

rising/templates/Trainer/login.html
<!DOCTYPE html>
{% extends 'loginBase.html' %}
{% load staticfiles %}
<body>
	{% block loginblock %}
	<div class="row">
		<div class="col-12">
			<ul class="nav nav-pills nav-fill">
					<li class="nav-item"><a href="{% url 'Trainer:user_login' %}" class="nav-link active">Trainer</a></li>
					<li class="nav-item"><a href="{% url 'Student:user_login' %}" class="nav-link">Student</a></li>
			</ul>
		</div>
	</div>
	<br>
	<div class="row">
		<div class="col-12">
			<form action="{% url 'Trainer:user_login' %}" method="post">
					{% csrf_token %}
					<div class="form-group">
						<labe for="username" >Username: </labe>
    					<input type="text" name="username" placeholder="enter username">
						<labe for="password" >password: </labe>
						<input type="text" name="password" placeholder="enter password">					
					</div>
					<input type="submit" name="" value="Login">
			</form>
		</div>
	</div>
	{% endblock %}
</body>

rising/templates/Trainer/registration.html
<!DOCTYPE html>
{% extends 'Trainer/base.html' %}
{% load staticfiles %}
{% block mainblock %}
<div class="jumbotron">
  {% if registered %}
  <p>thanks</p>
  {% else %}
  <p>register here</p>

  <form action="" method="post">
    {% csrf_token %}
    {{ user_form.as_p }}
    {{ profile_form.as_p }}
    <input type="submit" name="" value="Register">
  </form>
  {% endif %}
</div>
{% endblock %}

rising/templates/loginBase.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
<title>Login</title>
	<!-- <link rel="stylesheet" type="text/css" href="/css/bootstrap.min.css"> -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
body{
	background-size: cover;
	background: url(/img/bgGrievances.jpg);
}
h2{
	margin-top: 30px;
}
.container{
	height: 100vh;
	overflow: auto;
}
#row{
	margin-top:10%;
	margin-bottom: 20px;
}
#loginbox{
	padding-top: 5%;
	padding-bottom: 5%;
	background-color: rgba(0,0,0,0.02);
}
.form-group{
	max-width:275px;
	margin-left: 25%;
}
.form-control{
	height: 40px;
	font-size: 15px;
	line-height: 17px;
}
img{
	max-width:250px;
}
li{
	padding-left: 35px;
	padding-right: 35px;
}
</style>
</head>
<body>
  <div class="container text-center">
	<div class="row" id="row">
		<div class="col-6" style="padding-top: 7%;">
			<img src="http://ccet.ac.in/img/index/ccetLogoWhite.png" >
			<h2>Rising<br>Studio</h2>
		</div>

		<div class="col-6" id="loginbox">
		{% block loginblock %}
    {% endblock %}
		</div>
	</div>
	</div>
</body>
</html>

rising/templates/navbarBase.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <a class="navbar-brand" href="#">Brand Logo</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Dashboard <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <!-- <a class="nav-link" href="#">Profile</a> -->
            <a href="{% url 'Trainer:register' %}">register</a>
          </li>
        </ul>
      </div>
      <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <!-- <a class="nav-link" href="#">Logout</a> -->
                {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'logout' %}">logout</a>
                {% else %}
                <a class="nav_link" href="{% url 'Trainer:user_login' %}">login</a>
                {% endif %}
            </li>
        </ul>
    </div>
    </nav>
    {% block mainblock %}
    {% endblock %}
  </body>
</html>